alg: ppo
env: LunarLander-v2
frame_stack: null
git_link: https://github.com/elrorvik/test-hyperfetch
log_folder: logs
n_envs: 1
n_evaluations: 5
n_jobs: 1
n_min_trials: 1
n_startup_trials: 10
n_timesteps: 20000
n_trials: 10
n_warmup_steps: 10
policy: MlpPolicy
post_run: true
project_name: some_project
pruner: median
reward_threshold: null
sampler: tpe
seed: 0
trial_log_path: logs/trials
